version: '3'
services:
  mysql:
    build: ./mysql-srvc
    ports:
      - "6603:3306"
  nodejs:
    build: ./nodejs-srvc
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=mysql
    command: sh -c './wait-for.sh mysql:6603 -- npm start'